/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../fronted/routes/__root'
import { Route as WhatsappRouteImport } from './../fronted/routes/whatsapp'
import { Route as TenantAdminRouteImport } from './../fronted/routes/tenant-admin'
import { Route as TasksRouteImport } from './../fronted/routes/tasks'
import { Route as SuperAdminRouteImport } from './../fronted/routes/super-admin'
import { Route as SmsRouteImport } from './../fronted/routes/sms'
import { Route as SettingsRouteImport } from './../fronted/routes/settings'
import { Route as ResetPasswordRouteImport } from './../fronted/routes/reset-password'
import { Route as ReportsRouteImport } from './../fronted/routes/reports'
import { Route as QuotesRouteImport } from './../fronted/routes/quotes'
import { Route as ProposalsRouteImport } from './../fronted/routes/proposals'
import { Route as ProductsRouteImport } from './../fronted/routes/products'
import { Route as NotesRouteImport } from './../fronted/routes/notes'
import { Route as MeetingsRouteImport } from './../fronted/routes/meetings'
import { Route as LoginRouteImport } from './../fronted/routes/login'
import { Route as LeadsRouteImport } from './../fronted/routes/leads'
import { Route as InvoicesRouteImport } from './../fronted/routes/invoices'
import { Route as InboxRouteImport } from './../fronted/routes/inbox'
import { Route as ForgotPasswordRouteImport } from './../fronted/routes/forgot-password'
import { Route as FollowupsRouteImport } from './../fronted/routes/followups'
import { Route as EmailRouteImport } from './../fronted/routes/email'
import { Route as DocumentsRouteImport } from './../fronted/routes/documents'
import { Route as DealsRouteImport } from './../fronted/routes/deals'
import { Route as ContactsRouteImport } from './../fronted/routes/contacts'
import { Route as ClientsRouteImport } from './../fronted/routes/clients'
import { Route as CallsRouteImport } from './../fronted/routes/calls'
import { Route as CallLogsRouteImport } from './../fronted/routes/call-logs'
import { Route as CalendarRouteImport } from './../fronted/routes/calendar'
import { Route as AiAssistantRouteImport } from './../fronted/routes/ai-assistant'
import { Route as IndexRouteImport } from './../fronted/routes/index'
import { Route as ReportsPipelineRouteImport } from './../fronted/routes/reports.pipeline'
import { Route as ReportsPerformanceRouteImport } from './../fronted/routes/reports.performance'
import { Route as ReportsActivityRouteImport } from './../fronted/routes/reports.activity'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantAdminRoute = TenantAdminRouteImport.update({
  id: '/tenant-admin',
  path: '/tenant-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsRoute = SmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowupsRoute = FollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const CallLogsRoute = CallLogsRouteImport.update({
  id: '/call-logs',
  path: '/call-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsPipelineRoute = ReportsPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsPerformanceRoute = ReportsPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsActivityRoute = ReportsActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/calendar': typeof CalendarRoute
  '/call-logs': typeof CallLogsRoute
  '/calls': typeof CallsRoute
  '/clients': typeof ClientsRoute
  '/contacts': typeof ContactsRoute
  '/deals': typeof DealsRoute
  '/documents': typeof DocumentsRoute
  '/email': typeof EmailRoute
  '/followups': typeof FollowupsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inbox': typeof InboxRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/notes': typeof NotesRoute
  '/products': typeof ProductsRoute
  '/proposals': typeof ProposalsRoute
  '/quotes': typeof QuotesRoute
  '/reports': typeof ReportsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sms': typeof SmsRoute
  '/super-admin': typeof SuperAdminRoute
  '/tasks': typeof TasksRoute
  '/tenant-admin': typeof TenantAdminRoute
  '/whatsapp': typeof WhatsappRoute
  '/reports/activity': typeof ReportsActivityRoute
  '/reports/performance': typeof ReportsPerformanceRoute
  '/reports/pipeline': typeof ReportsPipelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/calendar': typeof CalendarRoute
  '/call-logs': typeof CallLogsRoute
  '/calls': typeof CallsRoute
  '/clients': typeof ClientsRoute
  '/contacts': typeof ContactsRoute
  '/deals': typeof DealsRoute
  '/documents': typeof DocumentsRoute
  '/email': typeof EmailRoute
  '/followups': typeof FollowupsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inbox': typeof InboxRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/notes': typeof NotesRoute
  '/products': typeof ProductsRoute
  '/proposals': typeof ProposalsRoute
  '/quotes': typeof QuotesRoute
  '/reports': typeof ReportsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sms': typeof SmsRoute
  '/super-admin': typeof SuperAdminRoute
  '/tasks': typeof TasksRoute
  '/tenant-admin': typeof TenantAdminRoute
  '/whatsapp': typeof WhatsappRoute
  '/reports/activity': typeof ReportsActivityRoute
  '/reports/performance': typeof ReportsPerformanceRoute
  '/reports/pipeline': typeof ReportsPipelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/calendar': typeof CalendarRoute
  '/call-logs': typeof CallLogsRoute
  '/calls': typeof CallsRoute
  '/clients': typeof ClientsRoute
  '/contacts': typeof ContactsRoute
  '/deals': typeof DealsRoute
  '/documents': typeof DocumentsRoute
  '/email': typeof EmailRoute
  '/followups': typeof FollowupsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inbox': typeof InboxRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/notes': typeof NotesRoute
  '/products': typeof ProductsRoute
  '/proposals': typeof ProposalsRoute
  '/quotes': typeof QuotesRoute
  '/reports': typeof ReportsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sms': typeof SmsRoute
  '/super-admin': typeof SuperAdminRoute
  '/tasks': typeof TasksRoute
  '/tenant-admin': typeof TenantAdminRoute
  '/whatsapp': typeof WhatsappRoute
  '/reports/activity': typeof ReportsActivityRoute
  '/reports/performance': typeof ReportsPerformanceRoute
  '/reports/pipeline': typeof ReportsPipelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/calendar'
    | '/call-logs'
    | '/calls'
    | '/clients'
    | '/contacts'
    | '/deals'
    | '/documents'
    | '/email'
    | '/followups'
    | '/forgot-password'
    | '/inbox'
    | '/invoices'
    | '/leads'
    | '/login'
    | '/meetings'
    | '/notes'
    | '/products'
    | '/proposals'
    | '/quotes'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/sms'
    | '/super-admin'
    | '/tasks'
    | '/tenant-admin'
    | '/whatsapp'
    | '/reports/activity'
    | '/reports/performance'
    | '/reports/pipeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/calendar'
    | '/call-logs'
    | '/calls'
    | '/clients'
    | '/contacts'
    | '/deals'
    | '/documents'
    | '/email'
    | '/followups'
    | '/forgot-password'
    | '/inbox'
    | '/invoices'
    | '/leads'
    | '/login'
    | '/meetings'
    | '/notes'
    | '/products'
    | '/proposals'
    | '/quotes'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/sms'
    | '/super-admin'
    | '/tasks'
    | '/tenant-admin'
    | '/whatsapp'
    | '/reports/activity'
    | '/reports/performance'
    | '/reports/pipeline'
  id:
    | '__root__'
    | '/'
    | '/ai-assistant'
    | '/calendar'
    | '/call-logs'
    | '/calls'
    | '/clients'
    | '/contacts'
    | '/deals'
    | '/documents'
    | '/email'
    | '/followups'
    | '/forgot-password'
    | '/inbox'
    | '/invoices'
    | '/leads'
    | '/login'
    | '/meetings'
    | '/notes'
    | '/products'
    | '/proposals'
    | '/quotes'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/sms'
    | '/super-admin'
    | '/tasks'
    | '/tenant-admin'
    | '/whatsapp'
    | '/reports/activity'
    | '/reports/performance'
    | '/reports/pipeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistantRoute: typeof AiAssistantRoute
  CalendarRoute: typeof CalendarRoute
  CallLogsRoute: typeof CallLogsRoute
  CallsRoute: typeof CallsRoute
  ClientsRoute: typeof ClientsRoute
  ContactsRoute: typeof ContactsRoute
  DealsRoute: typeof DealsRoute
  DocumentsRoute: typeof DocumentsRoute
  EmailRoute: typeof EmailRoute
  FollowupsRoute: typeof FollowupsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InboxRoute: typeof InboxRoute
  InvoicesRoute: typeof InvoicesRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  MeetingsRoute: typeof MeetingsRoute
  NotesRoute: typeof NotesRoute
  ProductsRoute: typeof ProductsRoute
  ProposalsRoute: typeof ProposalsRoute
  QuotesRoute: typeof QuotesRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SmsRoute: typeof SmsRoute
  SuperAdminRoute: typeof SuperAdminRoute
  TasksRoute: typeof TasksRoute
  TenantAdminRoute: typeof TenantAdminRoute
  WhatsappRoute: typeof WhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant-admin': {
      id: '/tenant-admin'
      path: '/tenant-admin'
      fullPath: '/tenant-admin'
      preLoaderRoute: typeof TenantAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms': {
      id: '/sms'
      path: '/sms'
      fullPath: '/sms'
      preLoaderRoute: typeof SmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followups': {
      id: '/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof FollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-logs': {
      id: '/call-logs'
      path: '/call-logs'
      fullPath: '/call-logs'
      preLoaderRoute: typeof CallLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/pipeline': {
      id: '/reports/pipeline'
      path: '/pipeline'
      fullPath: '/reports/pipeline'
      preLoaderRoute: typeof ReportsPipelineRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/performance': {
      id: '/reports/performance'
      path: '/performance'
      fullPath: '/reports/performance'
      preLoaderRoute: typeof ReportsPerformanceRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/activity': {
      id: '/reports/activity'
      path: '/activity'
      fullPath: '/reports/activity'
      preLoaderRoute: typeof ReportsActivityRouteImport
      parentRoute: typeof ReportsRoute
    }
  }
}

interface ReportsRouteChildren {
  ReportsActivityRoute: typeof ReportsActivityRoute
  ReportsPerformanceRoute: typeof ReportsPerformanceRoute
  ReportsPipelineRoute: typeof ReportsPipelineRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsActivityRoute: ReportsActivityRoute,
  ReportsPerformanceRoute: ReportsPerformanceRoute,
  ReportsPipelineRoute: ReportsPipelineRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistantRoute: AiAssistantRoute,
  CalendarRoute: CalendarRoute,
  CallLogsRoute: CallLogsRoute,
  CallsRoute: CallsRoute,
  ClientsRoute: ClientsRoute,
  ContactsRoute: ContactsRoute,
  DealsRoute: DealsRoute,
  DocumentsRoute: DocumentsRoute,
  EmailRoute: EmailRoute,
  FollowupsRoute: FollowupsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InboxRoute: InboxRoute,
  InvoicesRoute: InvoicesRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  MeetingsRoute: MeetingsRoute,
  NotesRoute: NotesRoute,
  ProductsRoute: ProductsRoute,
  ProposalsRoute: ProposalsRoute,
  QuotesRoute: QuotesRoute,
  ReportsRoute: ReportsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SmsRoute: SmsRoute,
  SuperAdminRoute: SuperAdminRoute,
  TasksRoute: TasksRoute,
  TenantAdminRoute: TenantAdminRoute,
  WhatsappRoute: WhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
