/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantAdminRouteImport } from './routes/tenant-admin'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FollowupsRouteImport } from './routes/followups'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'

const TenantAdminRoute = TenantAdminRouteImport.update({
  id: '/tenant-admin',
  path: '/tenant-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowupsRoute = FollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/contacts': typeof ContactsRoute
  '/deals': typeof DealsRoute
  '/followups': typeof FollowupsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/notes': typeof NotesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/super-admin': typeof SuperAdminRoute
  '/tasks': typeof TasksRoute
  '/tenant-admin': typeof TenantAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/contacts': typeof ContactsRoute
  '/deals': typeof DealsRoute
  '/followups': typeof FollowupsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/notes': typeof NotesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/super-admin': typeof SuperAdminRoute
  '/tasks': typeof TasksRoute
  '/tenant-admin': typeof TenantAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/contacts': typeof ContactsRoute
  '/deals': typeof DealsRoute
  '/followups': typeof FollowupsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/notes': typeof NotesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/super-admin': typeof SuperAdminRoute
  '/tasks': typeof TasksRoute
  '/tenant-admin': typeof TenantAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/ai-assistant'
    | '/calendar'
    | '/clients'
    | '/contacts'
    | '/deals'
    | '/followups'
    | '/forgot-password'
    | '/leads'
    | '/login'
    | '/manager'
    | '/notes'
    | '/reset-password'
    | '/sales'
    | '/set-password'
    | '/settings'
    | '/super-admin'
    | '/tasks'
    | '/tenant-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/ai-assistant'
    | '/calendar'
    | '/clients'
    | '/contacts'
    | '/deals'
    | '/followups'
    | '/forgot-password'
    | '/leads'
    | '/login'
    | '/manager'
    | '/notes'
    | '/reset-password'
    | '/sales'
    | '/set-password'
    | '/settings'
    | '/super-admin'
    | '/tasks'
    | '/tenant-admin'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/ai-assistant'
    | '/calendar'
    | '/clients'
    | '/contacts'
    | '/deals'
    | '/followups'
    | '/forgot-password'
    | '/leads'
    | '/login'
    | '/manager'
    | '/notes'
    | '/reset-password'
    | '/sales'
    | '/set-password'
    | '/settings'
    | '/super-admin'
    | '/tasks'
    | '/tenant-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AiAssistantRoute: typeof AiAssistantRoute
  CalendarRoute: typeof CalendarRoute
  ClientsRoute: typeof ClientsRoute
  ContactsRoute: typeof ContactsRoute
  DealsRoute: typeof DealsRoute
  FollowupsRoute: typeof FollowupsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  NotesRoute: typeof NotesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SalesRoute: typeof SalesRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SuperAdminRoute: typeof SuperAdminRoute
  TasksRoute: typeof TasksRoute
  TenantAdminRoute: typeof TenantAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenant-admin': {
      id: '/tenant-admin'
      path: '/tenant-admin'
      fullPath: '/tenant-admin'
      preLoaderRoute: typeof TenantAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followups': {
      id: '/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof FollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AiAssistantRoute: AiAssistantRoute,
  CalendarRoute: CalendarRoute,
  ClientsRoute: ClientsRoute,
  ContactsRoute: ContactsRoute,
  DealsRoute: DealsRoute,
  FollowupsRoute: FollowupsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  NotesRoute: NotesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SalesRoute: SalesRoute,
  SetPasswordRoute: SetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SuperAdminRoute: SuperAdminRoute,
  TasksRoute: TasksRoute,
  TenantAdminRoute: TenantAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
